services:
  rag-builder:
    build: .
    image: rag-builder-spd:latest
    container_name: rag-builder-spd-dev

    env_file:
      - .env

    environment:
      POSTGRES_HOST: host.docker.internal
      EMBEDDING_API_BASE_URL: ${EMBEDDING_BASE_URL:-https://routerai.ru/api/v1}
      EMBEDDING_API_KEY: ${ROUTERAI_API_KEY:-}

    ports:
      - "8001:8000"

    restart: unless-stopped