#!/bin/sh
set -eu

cat > /app/.env <<EOF
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
DB_DATABASE=${DB_DATABASE}
DATABASE_URL=${DATABASE_URL}
EOF

exec "$@"
