#!/usr/bin/env python3
"""
Генерация docker/.env для Docker Compose.

Читает переменные из docker-compose.yml (x-env-common) и добавляет
обязательные DEFAULT_ADMIN_* (их нет в compose-якоре).

Запуск: python create_env.py
"""
import os

DOTENV_PATH = os.path.join(os.path.dirname(__file__), ".env")

# Переменные, которых нет в x-env-common docker-compose.yml,
# но обязательны в .env для работы сервисов
EXTRA_VARS: dict[str, str] = {
    # =============================================================================
    # PKB Neuroassistant — Docker Environment
    # =============================================================================
    #
    # Auto-generated by create_env.py
    #
    # ── Auth Service (admin seed) ─────────────────────────────────────────
    "DEFAULT_ADMIN_EMAIL": "admin@example.com",
    "DEFAULT_ADMIN_PASSWORD": "Admin1234!",
    # ── Database ──────────────────────────────────────────────────────────
    "DB_HOST": "postgres",
    "DB_PORT": "5432",
    "DB_USERNAME": "pkb",
    "DB_PASSWORD": "pkb",
    "DB_DATABASE": "pkb_neuro",
    "DATABASE_URL": "postgresql+asyncpg://pkb:pkb@postgres:5432/pkb_neuro",
    "DB_SUPERUSER": "postgres",
    # ── Redis ─────────────────────────────────────────────────────────────
    "REDIS_URL": "redis://redis:6379/0",
    "CELERY_BROKER_URL": "redis://redis:6379/1",
    "CELERY_RESULT_BACKEND": "redis://redis:6379/2",
    # ── MinIO ─────────────────────────────────────────────────────────────
    "MINIO_ENDPOINT": "minio:9000",
    "MINIO_ACCESS_KEY": "minioadmin",
    "MINIO_SECRET_KEY": "minioadmin",
    "MINIO_BUCKET": "documents",
    "MINIO_IMAGE_BUCKET": "images",
    "MINIO_SECURE": "false",
    # ── Auth: Rate Limit ────────────────────────────────────────────────
    "RATE_LIMIT_REQUESTS": "200",
    "RATE_LIMIT_WINDOW_SECONDS": "60",
    # ── Auth: Brute-force protection ──────────────────────────────────
    "MAX_FAILED_ATTEMPTS": "100",
    "LOCKOUT_DURATION_SECONDS": "0",
    # ── Auth Mock ─────────────────────────────────────────────────────────
    "AUTH_SERVICE_MOCK": "false",
    "DEV_AUTH_MODE": "false",
    "MOCK_LLM_ENABLED": "false",
    "REGISTRY_SERVICE_MOCK": "false",
    "JWT_SECRET_KEY": "pkb-neuroassistant-jwt-secret-key-2026-dev",
    "JWT_ALGORITHM": "HS256",
    # ── Embedding (TEI) ──────────────────────────────────────────────────
    "EMBEDDING_PROVIDER": "tei",
    "EMBEDDING_BASE_URL": "http://tei:80",
    "EMBEDDING_MODEL": "Vuy/rubert-tiny2-onnx",
    "EMBEDDING_DIM": "312",
    "EMBEDDING_API_KEY": "sk-noop",
    # ── Search ────────────────────────────────────────────────────────────
    "SEARCH_DEFAULT_TOP_K": "10",
    "SEARCH_MAX_TOP_K": "100",
    # ── Service URLs ──────────────────────────────────────────────────────
    # Без /api/v1 — сервисы (Orchestrator и др.) сами добавляют путь
    # Внутри Docker — имена сервисов (docker-compose).
    # На хосте checker использует свои MODE_PORTS, не этот .env.
    "REGISTRY_SERVICE_URL": "http://127.0.0.1:8084",
    "INTEGRATION_SERVICE_URL": "http://127.0.0.1:8085",
    "VALIDATE_SERVICE_URL": "http://127.0.0.1:8086",
    "RAG_SERVICE_URL": "http://127.0.0.1:8091",
    "DATABASE_URL": "postgresql+asyncpg://pkb:pkb@postgres:5432/pkb_neuro",
    "RATE_LIMIT_ENABLED": "false",
    "APP_VERSION": "1.0.0",
}


def main():
    lines: list[str] = []
    # Не пишем заголовок — Docker может читать .env построчно
    for key, value in EXTRA_VARS.items():
        lines.append(f"{key}={value}")

    content = "\n".join(lines) + "\n"

    with open(DOTENV_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"  ✓ {DOTENV_PATH} ({len(EXTRA_VARS)} vars)")


if __name__ == "__main__":
    main()
