FROM python:3.13-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir huggingface_hub && rm -rf /root/.cache

WORKDIR /work

CMD ["python", "prepare_tei_model.py"]
