services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pkb-rag-frontend:latest
    container_name: pkb-rag-frontend
    ports:
      - "3300:80"
    develop:
      watch:
        - path: ./src
          action: rebuild
        - path: ./package.json
          action: rebuild
